[package]
name = "somethingRust"
version = "0.1.0"
edition = "2021"
authors = ["Julian <julianjpit@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.2"
regex = "1.5.5"